### ISSUE TITLE
Module doesn't work

### ISSUE THREAD

**Issue by giggin** [TerableCoder/cmd-channel#1]
[13:41:19.501] [dispatch] handle: error running raw hook for S_LOGIN<raw>
hook: (anonymous) in tera-game-state
data: df0120fe0200a70135014701200067014000fa2a00004e171a00008000001a0000005c880000000000000100000000320000006900000065010000101a040001004400010000005e010000000000005e0100005e0100000100000000000100000065459ffe10000000b34cbecf06000000f36d49f207000000980100007c3f330000000000913b0000961c7d00d9ca370c0000803f00000000405a01004c5a01000b5b01005c5a010065150300f25a01003e5a01005da62106000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000001b0da030028980200000000002dba020094da03000000000000000000010000000000000000640000000000803f000000004700690072006100660066006e006f000000000a080c000000001a121a000a15050010000c0d0000000f1517101519100e090113101313101313130f0f0f0f0f0f0f10130a00050b100000000000000000000000000000000000000000000000000000000000000000000000000000000000a701c3010b2200000000000070000000000000004400000000000000c3010000e825000000000000f4030000010000009300000001000000
error: [dispatch] hook: unmapped packet "S_PREPARE_SELECT_CHANNEL"
    at hook (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\cmd-channel-master\index.js:76:35)
    at load (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\cmd-channel-master\index.js:81:4)
    at TeraGameState.<anonymous> (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\cmd-channel-master\index.js:16:4)
    at TeraGameState.emit (events.js:199:15)
    at TeraGameState.setState (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\tera-game-state\index.js:104:46)
    at Object.callback (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\tera-game-state\index.js:87:86)
[13:45:49.704] [command] ERROR: Error: [dispatch] write: failed to generate C_SELECT_CHANNEL<1>:
Error: code not known for message "C_SELECT_CHANNEL"
    at Dispatch.write (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:376:23)
    at Module.send (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:156:30)
    at String.<anonymous> (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\cmd-channel-master\index.js:62:9)
    at CommandBase.exec (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:183:16)
    at hookCommand (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:61:30)
    at Object.callback (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\mods\command\index.js:71:29)
    at Dispatch.handle (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:466:45)
    at Socket.<anonymous> (C:\Users\x\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-network-proxy\lib\clients\RealClient.js:38:31)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)

**Comment by TerableCoder** [comment]
You don't have the opcodes for the module. I'll add NA's opcodes to https://github.com/TerableCoder/TerableOpcodes once patch 82 hits.
